-- drop table if not exists order items;
-- drop table if not exists orders;
-- drop table if not exists products;
-- drop table if not exists users;



-- create table users(
--     id integer generated always as identity primary key,
--     name text not null,
--     email text not null unique,
--     age integer check(age >=0 and age<150),
--     city text,
--     created_at timestamptz not null default now()
-- );

-- insert into users(name,email,age,city) values('Rajesh' , 'rasq122@gamil.com' , 25 ,'Birgunj') returning *;

-- insert into users (name,email) values (NULL,'x@gmail.com');

-- insert into users(name , email) values ('Sita' , 'sita@example.com');
-- insert into users(name,email)values('Other Sita' , 'sita@example.com');

-- insert into users (name,email,age) values ('baby','baby@example.com',-1);
-- INSERT INTO users (name, email, age) VALUES ('Old', 'old@x.com', 200);

-- INSERT INTO users (name, email) VALUES ('A', NULL);

-- INSERT INTO users (name, email) VALUES ('NoEmail1', NULL);   -- ERROR (NOT NULL)


-- drop table if exists test_unique;
-- create table test_unique(
--     id integer generated always as identity primary key,
--     tag text unique
-- );

-- insert into test_unique(tag)values(NULL),(NULL),(NULL);
-- select * from test_unique;

-- INSERT INTO test_unique (tag) VALUES ('a'), ('a');   -- ERROR (duplicate 'a')

-- DROP TABLE test_unique;

-- INSERT INTO users (id, name, email) VALUES (999, 'Forced', 'f@f.com');

-- INSERT INTO users (id, name, email)
-- OVERRIDING SYSTEM VALUE
-- VALUES (999, 'Forced', 'f@f.com');

-- DELETE FROM users WHERE id = 999;

-- DROP TABLE IF EXISTS test_ident;
-- CREATE TABLE test_ident (
--   id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   name TEXT
-- );
-- INSERT INTO test_ident (id, name) VALUES (100, 'manual-ok');
-- INSERT INTO test_ident (name)     VALUES ('auto');    -- continues from 101
-- SELECT * FROM test_ident;
-- DROP TABLE test_ident;

-- SELECT id, name, created_at FROM users ORDER BY id;
-- INSERT INTO users (name, email, created_at)VALUES ('Backdated', 'back@x.com', '2020-01-01 00:00:00+00')RETURNING id, created_at;

-- INSERT INTO users (name, email, age) VALUES ('Bad', 'bad@x.com', 'twenty-five');


-- DROP TABLE IF EXISTS order_items;
-- DROP TABLE IF EXISTS orders;
-- DROP TABLE IF EXISTS products;

-- CREATE TABLE products (
--   id        INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--   name      TEXT         NOT NULL,
--   price     NUMERIC(10,2) NOT NULL CHECK (price >= 0),
--   category  TEXT          NOT NULL,
--   stock     INTEGER       NOT NULL DEFAULT 0 CHECK (stock >= 0)
-- );

-- CREATE TABLE orders (
--   id         INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--   user_id    INTEGER      NOT NULL,
--   status     TEXT         NOT NULL DEFAULT 'pending'
--                CHECK (status IN ('pending','paid','shipped','delivered','cancelled')),
--   total      NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (total >= 0),
--   created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
-- );

-- CREATE TABLE order_items (
--   id         INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--   order_id   INTEGER       NOT NULL,
--   product_id INTEGER       NOT NULL,
--   quantity   INTEGER       NOT NULL CHECK (quantity > 0),
--   price      NUMERIC(10,2) NOT NULL CHECK (price >= 0)
-- );


-- -- CHECK on price
-- INSERT INTO products (name, price, category) VALUES ('Bad', -5, 'x');
-- -- ERROR: violates check constraint "products_price_check"

-- -- CHECK on status
-- INSERT INTO orders (user_id, status) VALUES (1, 'paid_ish');
-- -- ERROR: violates check constraint "orders_status_check"

-- -- CHECK on quantity
-- INSERT INTO order_items (order_id, product_id, quantity, price)
-- VALUES (1, 1, 0, 10);
-- -- ERROR: violates check constraint "order_items_quantity_check"














-- schema.sql — Day 3 version (IDENTITY + constraints)
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id         INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name       TEXT        NOT NULL,
  email      TEXT        NOT NULL UNIQUE,
  age        INTEGER     CHECK (age >= 0 AND age < 150),
  city       TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE products (
  id       INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name     TEXT          NOT NULL,
  price    NUMERIC(10,2) NOT NULL CHECK (price >= 0),
  category TEXT          NOT NULL,
  stock    INTEGER       NOT NULL DEFAULT 0 CHECK (stock >= 0)
);

CREATE TABLE orders (
  id         INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id    INTEGER       NOT NULL,
  status     TEXT          NOT NULL DEFAULT 'pending'
                             CHECK (status IN ('pending','paid','shipped','delivered','cancelled')),
  total      NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (total >= 0),
  created_at TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE TABLE order_items (
  id         INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  order_id   INTEGER       NOT NULL,
  product_id INTEGER       NOT NULL,
  quantity   INTEGER       NOT NULL CHECK (quantity > 0),
  price      NUMERIC(10,2) NOT NULL CHECK (price >= 0)
);